version: '3.8'

services:
  djangoserver:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: Backend
    volumes:
      - .:/app
    depends_on:
      - redis
      #- celery
    


  redis:
    image: redis:7.2.3-alpine3.18
    container_name: redisserver


  celery:
    image: celery:4.0.2
    container_name: celeryServer
    build: .
    depends_on:
      - redis
      - djangoserver
      
    volumes:
      - .:/app
    command: celery -A project worker --loglevel=info
    environment:
      - CELERY_BROKER_URL = 'redis://redis:6379/0'
      - CELERY_BACKEND_RESULTS = 'redis://redis:6379/0'
  

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=amazon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgres/data


volumes:
  postgres_data: